# Generated by Django 5.2 on 2025-05-28 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0002_veiculo_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veiculo',
            options={'ordering': ('-id',)},
        ),
    ]
